export const slideData = [
    { 
        title: "Portrait Sketching", 
        description: "Portrait painting is a genre in painting, where the intent is to represent a specific human subject.", 
        imgUrl: "./images/banner/slider1.jpg"
    },
    { 
        title: "Marker Sketching", 
        description: "Art markers are used by illustrators, designers and artists to achieve a different result in artwork than you would normally see from using colored pencils or paints.", 
        imgUrl:"./images/banner/slider2.jpg"
    },
    { 
        title: "Photography", 
        description: "Photography is the art, application, and practice of creating durable images by recording light, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film.", 
        imgUrl: "./images/banner/slider3.jpg"
    },
  ];

  export const indiamapCardData = [
    { 
        title: "Indian Culture Map",
        quotedescription: "India is the cradle of the human race, the birthplace of human speech, the mother of history, the grandmother of legend, and the great grand mother of tradition.", 
        description: "The Indian culture, often labeled as an amalgamation of several various cultures, spans across the Indian subcontinent and has been influenced and shaped by a history that is several thousand years old.", 
        imgUrl: "./images/art/indiamap.jpg",
        artdate: "20-08-2018",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"black",
        abouttext:"About India",
        aboutUrl:"https://en.wikipedia.org/wiki/India",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-up",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const indiaarmysoldierCardData = [
    { 
        title: "Indian Army Soldier",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The Indian Army is the land-based branch and the largest component of the Indian Armed Forces. The President of India is the Supreme Commander of the Indian Army, and its professional head is the Chief of Army Staff, who is a four-star general.", 
        imgUrl:"./images/art/armyman.jpg",
        artdate:"30-08-2018",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About Indian Army",
        aboutUrl:"https://en.wikipedia.org/wiki/Indian_Army",
        bordercolor:"bordercolorpurple",
        carddirection:"fade-down",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const jokersCardData = [
    { 
        title: "Positive shade Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Positive space refers to the shape of an object. Look around your room. Every object that you are looking at is creating positive space. Don’t worry about the patterns or details of the item, just focus on the shape of the object.", 
        imgUrl:"./images/art/jokerpositive.jpg",
        artdate:"09-08-2020",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Negative shade Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Negative space refers to the shape around an object. It can be much harder to look at an object. Look around the room for an object up against a wall and try to focus on the shape created on the wall around the object.", 
        imgUrl:"./images/art/jokernegative.jpg",
        artdate:"09-08-2020",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];

  export const pulvamathreeCardData = [
    { 
        title: "Pulvama Attack",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Pulwama attack is one of the deadliest terror attacks in Jammu and Kashmir in which 40 Central Reserve Police Force (CRPF) personnel were martyred. The Pulwama attack happened on February 14, 2019, when a Jaish suicide bomber rammed a vehicle carrying over 100 kg of explosives into their bus in Pulwama district.", 
        imgUrl:"./images/art/pulwama.jpg",
        artdate:"11-03-2019",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Indian Army Weapon",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The AK-47 203 is the latest and most advanced version of the AK-47 rifle, which will replace the Indian Small Arms System (INSAS) 5.56x45 mm assault rifle. India has one of the longest military histories, dating back several millennia.", 
        imgUrl:"./images/art/armygunhat.jpg",
        artdate:"28-05-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000",
    },
    { 
        title: "Indian Army Fitness",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The minimum acceptable height for Male candidate is 157.5 cms. For women candidate's minimum acceptable height is 152 cms. For Gorkhas and individuals belonging to hills of North Eastern region of India, Garhwali and Kumaon, the Minimum acceptable height will be 5 cms less.", 
        imgUrl:"./images/art/bodybuilder.jpg",
        artdate:"28-05-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];

  export const armysniperCardData = [
    { 
        title: "Indian army Sniper",
        quotedescription: "The enemy are only 50 yards from us. We are heavily outnumbered. We are under devastating fire. I shall not withdraw an inch but will fight to our last man and our last round. — Indian Army.", 
        description: "New Delhi: Elite units of the Indian Army, equipped with deadly new sniper rifles, have been deployed along the Line of Control with Pakistan after special training from American and Italian experts. Sources in the Army told ThePrint that units carrying the Beretta . 338 Lapua Magnum Scorpio TGT and the Barrett", 
        imgUrl:"./images/art/pubggun.jpg",
        artdate:"02-05-2018",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"black",
        abouttext:"About Indian Military",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];