export const slideData = [
    { 
        title: "Portrait Sketching", 
        description: "Portrait painting is a genre in painting, where the intent is to represent a specific human subject.", 
        imgUrl: "./images/banner/slider1.jpg"
    },
    { 
        title: "Marker Sketching", 
        description: "Art markers are used by illustrators, designers and artists to achieve a different result in artwork than you would normally see from using colored pencils or paints.", 
        imgUrl:"./images/banner/slider2.jpg"
    },
    { 
        title: "Photography", 
        description: "Photography is the art, application, and practice of creating durable images by recording light, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film.", 
        imgUrl: "./images/banner/slider3.jpg"
    },
  ];

  export const indiamapCardData = [
    { 
        title: "Indian Culture Map",
        quotedescription: "India is the cradle of the human race, the birthplace of human speech, the mother of history, the grandmother of legend, and the great grand mother of tradition.", 
        description: "The Indian culture, often labeled as an amalgamation of several various cultures, spans across the Indian subcontinent and has been influenced and shaped by a history that is several thousand years old.", 
        imgUrl: "./images/art/indiamap.jpg",
        artdate: "20-08-2018",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"black",
        abouttext:"About India",
        aboutUrl:"https://en.wikipedia.org/wiki/India",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-up",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const indiaarmysoldierCardData = [
    { 
        title: "Indian Army Soldier",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The Indian Army is the land-based branch and the largest component of the Indian Armed Forces. The President of India is the Supreme Commander of the Indian Army, and its professional head is the Chief of Army Staff, who is a four-star general.", 
        imgUrl:"./images/art/armyman.jpg",
        artdate:"30-08-2018",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About Indian Army",
        aboutUrl:"https://en.wikipedia.org/wiki/Indian_Army",
        bordercolor:"bordercolorpurple",
        carddirection:"fade-down",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const jokersCardData = [
    { 
        title: "Positive shade Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Positive space refers to the shape of an object. Look around your room. Every object that you are looking at is creating positive space. Don’t worry about the patterns or details of the item, just focus on the shape of the object.", 
        imgUrl:"./images/art/jokerpositive.jpg",
        artdate:"09-08-2020",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Negative shade Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Negative space refers to the shape around an object. It can be much harder to look at an object. Look around the room for an object up against a wall and try to focus on the shape created on the wall around the object.", 
        imgUrl:"./images/art/jokernegative.jpg",
        artdate:"09-08-2020",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];

  export const pulvamathreeCardData = [
    { 
        title: "Pulvama Attack",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Pulwama attack is one of the deadliest terror attacks in Jammu and Kashmir in which 40 Central Reserve Police Force (CRPF) personnel were martyred. The Pulwama attack happened on February 14, 2019, when a Jaish suicide bomber rammed a vehicle carrying over 100 kg of explosives into their bus in Pulwama district.", 
        imgUrl:"./images/art/pulwama.jpg",
        artdate:"11-03-2019",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Indian Army Weapon",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The AK-47 203 is the latest and most advanced version of the AK-47 rifle, which will replace the Indian Small Arms System (INSAS) 5.56x45 mm assault rifle. India has one of the longest military histories, dating back several millennia.", 
        imgUrl:"./images/art/armygunhat.jpg",
        artdate:"28-05-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000",
    },
    { 
        title: "Indian Army Fitness",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The minimum acceptable height for Male candidate is 157.5 cms. For women candidate's minimum acceptable height is 152 cms. For Gorkhas and individuals belonging to hills of North Eastern region of India, Garhwali and Kumaon, the Minimum acceptable height will be 5 cms less.", 
        imgUrl:"./images/art/bodybuilder.jpg",
        artdate:"28-05-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];

  export const armysniperCardData = [
    { 
        title: "Indian army Sniper",
        quotedescription: "The enemy are only 50 yards from us. We are heavily outnumbered. We are under devastating fire. I shall not withdraw an inch but will fight to our last man and our last round. — Indian Army.", 
        description: "New Delhi: Elite units of the Indian Army, equipped with deadly new sniper rifles, have been deployed along the Line of Control with Pakistan after special training from American and Italian experts. Sources in the Army told ThePrint that units carrying the Beretta . 338 Lapua Magnum Scorpio TGT and the Barrett", 
        imgUrl:"./images/art/pubggun.jpg",
        artdate:"02-05-2018",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About Indian Military",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const actorsCardData = [
    { 
        title: "Sachin Tendulkar Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Sachin Ramesh Tendulkar is an Indian former international cricketer who served as captain of the Indian national team.", 
        imgUrl:"./images/art/sachintendulkar.jpg",
        artdate:"06-07-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"white",
        abouttext:"About",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Actor Yash Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Naveen Kumar Gowda, known by the stage name Yash, is an Indian film actor who works in Kannada cinema.", 
        imgUrl:"./images/art/yash.jpg",
        artdate:"10-01-2018",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];

  export const godsthreeCardData = [
    { 
        title: "God Hanuman",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Hanuman (Sanskrit: हनुमान्, IAST: Hanumān) is a Hindu god and divine vanara companion of the god Rama. Hanuman is one of the central characters of the Hindu epic Ramayana.", 
        imgUrl:"./images/art/hanuman.jpg",
        artdate:"20-04-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Lord Sri Ram",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Rama (or Ramacandra) is the seventh avatar of the Hindu god Vishnu. Lord Rama, considered by many Hindus to be based on an historical story, are a picture of purity.", 
        imgUrl:"./images/art/ram.jpg",
        artdate:"23-06-2019",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000",
    },
    { 
        title: "Lord Shiva",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Shiva (or Siva) is one of the most important gods in the Hindu pantheon and, along with Brahma and Vishnu, is considered a member of the holy trinity (trimurti) of Hinduism.", 
        imgUrl:"./images/art/shiva.jpg",
        artdate:"15-08-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];


  export const teareyeCardData = [
    { 
        title: "Emotional Eye Tears",
        quotedescription: "When someone is crying, of course, the noble thing to do is to comfort them. But if someone is trying to hide their tears, it may also be noble to pretend you do not notice them.", 
        description: "The value of crying may be more about the social response it prompts than its physiological effects,” says Lauren Bylsma, PhD, University of Pittsburgh. Dr. Bylsma has conducted multiple studies on crying and found that people were more likely to feel better after crying if they received social support during their tears.", 
        imgUrl:"./images/art/eye.jpg",
        artdate:"02-05-2020",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About Tears",
        aboutUrl:"https://en.wikipedia.org/wiki/Indian_Army",
        bordercolor:"bordercolorpurple",
        carddirection:"fade-down",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];


  export const waterdropomCardData = [
    { 
        title: "Water scarcity and poverty",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "India's water crisis is often attributed to lack of government planning, increased corporate privatization, industrial and human waste and government corruption. In addition, water scarcity in India is expected to worsen as the overall population is expected to increase to 1.6 billion by year 2050.", 
        imgUrl:"./images/art/glassdrop.jpg",
        artdate:"31-03-2018",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"black",
        abouttext:"About Water Scarcity",
        aboutUrl:"https://en.wikipedia.org/wiki/Water_scarcity",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Om Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Om is a mantra that is traditionally chanted at the beginning and end of yoga sessions. With roots in Hinduism, When pronounced correctly, it sounds more like 'AUM'. The meaning and connotations of Om vary between the diverse schools within and across the various traditions.", 
        imgUrl:"./images/art/omm.jpg",
        artdate:"02-05-2020",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About",
        aboutUrl:"https://en.wikipedia.org/wiki/Om",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];


  export const jokerhrithikthreeCardData = [
    { 
        title: "Joker Paint",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The Joker is a supervillain created by Bill Finger, Bob Kane, and Jerry Robinson who first appeared in the debut issue of the comic book Batman (April 25, 1940). Credit for the Joker's creation is disputed.", 
        imgUrl:"./images/art/jokerface.jpg",
        artdate:"28-05-2020",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Hrithik Roshan",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Hrithik Roshan is an Indian actor known for his work in Hindi films. As a child, he made uncredited appearances in three films directed by his maternal grandfather, J. Om Prakash, the first of which was in Aasha (1980). In 1986.", 
        imgUrl:"./images/art/hrithik.jpg",
        artdate:"26-09-2020",
        artworkcategory:"Portrait Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000",
    },
    { 
        title: "Wolworine",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "The minimum acceptable height for Male candidate is 157.5 cms. For women candidate's minimum acceptable height is 152 cms. For Gorkhas and individuals belonging to hills of North Eastern region of India, Garhwali.", 
        imgUrl:"./images/art/wolworine.jpg",
        artdate:"04-04-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];


  export const bottleEgleCardData = [
    { 
        title: "Bottle Pencil Sketch",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "This sketch may serve a number of purposes: it might record something that the artist sees, it might record or develop an idea.", 
        imgUrl:"./images/art/bottle.jpg",
        artdate:"05-06-2019",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
    { 
        title: "Egle Bird",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "Eagle is the common name for many large birds of prey of the family Accipitridae. Most of the eagles are from Eurasia and Africa.", 
        imgUrl:"./images/art/egle.jpg",
        artdate:"01-08-2017",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"center",
        artworkpadding:'0px',
        arttextcolor:"white",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000",
    },
    { 
        title: "Sparrow",
        quotedescription: "To other countries, I may go as a tourist, but to India, I come as an Indian Solider. — Indian Army.", 
        description: "A sparrow is a member of the genus Passer. They are small passerine birds which belong to the family Passeridae.", 
        imgUrl:"./images/art/singlebird.jpg",
        artdate:"30-12-2019",
        artworkcategory:"Pencil Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About This Art",
        aboutUrl:"https://www.artinstructionblog.com/an-introduction-to-negative-drawing-with-mike-sibley",
        bordercolor:"bordercolormaroon",
        carddirection:"fade-left",
        imagedirection:"flip-left",
        textdirection:"fade-left",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    }
  ];

  export const lovebirdsCardData = [
    { 
        title: "Love Birds",
        quotedescription: "The Love bird is one hundred percent faithful to his mate-who is locked into the same cage.", 
        description: "A lovebird might be one of the smaller parrot species available as a companion pet, but this bird is inquisitive and seemingly always on the go.", 
        imgUrl:"./images/art/lovebird.jpg",
        artdate:"04-04-2017",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"white",
        abouttext:"About",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const singlealoneCardData = [
    { 
        title: "Alone Life",
        quotedescription: "Sometimes, you need to be alone. Not to be lonely, but to enjoy your time being yourself.", 
        description: "Loneliness can be normal, and is only an indicator of underlying disease when feelings become excessive, all-consuming and interfere with daily living.", 
        imgUrl:"./images/art/aloneman.jpg",
        artdate:"08-08-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-end",
        artworkpadding:'0px 20px 0px 0px',
        arttextcolor:"white",
        abouttext:"About",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const redeyeCardData = [
    { 
        title: "RedEye",
        quotedescription: "We get high to get by, hot dogs no rib eyes, with tears dripped from red eyes, where ends don't meet the dealines.", 
        description: "Red eyes are usually caused by allergy, eye fatigue, over-wearing contact lenses, or common eye infections such as pink eye (conjunctivitis).", 
        imgUrl:"./images/art/redeye.jpg",
        artdate:"08-03-2018",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"white",
        abouttext:"About",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const racingCardData = [
    { 
        title: "Racing",
        quotedescription: "My prince charming doesn’t ride a horse he rides wheelies.", 
        description: "In sport, racing is a competition of speed, against an objective criterion, usually a clock or to a specific point. A race may be run continuously to finish or may be made of several segments called heats, stages or legs.", 
        imgUrl:"./images/art/racebike.jpg",
        artdate:"10-09-2017",
        artworkcategory:"Marker Sketch",
        artworkposition:"bottom",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"white",
        abouttext:"About Racing",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];


  export const beachCardData = [
    { 
        title: "Beach",
        quotedescription: "At the beach, life is different. Time doesn’t move hour to hour but mood to moment. We live by the currents, plan by the tides and follow the sun.", 
        description: "A beach is a landform alongside a body of water which consists of loose particles. The particles composing a beach are typically made from rock, such as sand, gravel, shingle, pebbles, etc, or biological sources, such as mollusc shells or coralline algae.", 
        imgUrl:"./images/photography/beach.jpg",
        artdate:"08-08-2017",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About Beach",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];

  export const beachbikeCardData = [
    { 
        title: "Beach Adventure",
        quotedescription: "To escape and sit quietly on the beach – that's my idea of paradise.", 
        description: "At the beach, life is different. Time doesn’t move hour to hour but mood to moment. We live by the currents, plan by the tides and follow the sun.", 
        imgUrl:"./images/photography/beachride.jpg",
        artdate:"08-08-2017",
        artworkcategory:"Pencil Sketch",
        artworkposition:"top",
        artworkdisplay:"flex-start",
        artworkpadding:'0px 0px 0px 20px',
        arttextcolor:"black",
        abouttext:"About",
        aboutUrl:"https://en.wikipedia.org/wiki/List_of_equipment_of_the_Indian_Army",
        bordercolor:"bordercoloraqua",
        carddirection:"fade-right",
        imagedirection:"flip-right",
        textdirection:"fade-right",
        borderdirection:"zoom-in",
        onesecondDuration: "1000",
        twosecondDuration: "2000",
        threesecondDuration: "3000",
        foursecondDuration: "4000"
    },
  ];